services:
  db:
    image: postgres:15-alpine
    container_name: test_db
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: test_logistics
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_logistics"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: test_backend
    # Sesuaikan dengan port yang kamu pakai di Go (Fiber)
    ports:
      - "8080:8080" 
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: test_logistics
      DB_USER: test_user
      DB_PASSWORD: password123  
      JWT_SECRET: TesTingFullStack321
      PORT: 8080

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: test_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080/api
    depends_on:
      - backend